# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Googleui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_googlegui(object):
    def setupUi(self, googlegui):
        googlegui.setObjectName("googlegui")
        googlegui.resize(1121, 865)
        self.centralwidget = QtWidgets.QWidget(googlegui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1141, 861))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("f48e7a6487df38a0aed24fec6c4adbff (1).gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1141, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ProtoPie-voice-feature-visualization-gif (1).gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 760, 751, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("xiaoyi-status.gif"))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-10, 740, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 730, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 640, 256, 91))
        self.textBrowser.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(790, 630, 256, 91))
        self.textBrowser_2.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        googlegui.setCentralWidget(self.centralwidget)

        self.retranslateUi(googlegui)
        QtCore.QMetaObject.connectSlotsByName(googlegui)

    def retranslateUi(self, googlegui):
        _translate = QtCore.QCoreApplication.translate
        googlegui.setWindowTitle(_translate("googlegui", "MainWindow"))
        self.pushButton.setText(_translate("googlegui", "RUN"))
        self.pushButton_2.setText(_translate("googlegui", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    googlegui = QtWidgets.QMainWindow()
    ui = Ui_googlegui()
    ui.setupUi(googlegui)
    googlegui.show()
    sys.exit(app.exec_())
